#!/usr/bin/env python3
from random import choice as rc
# This line imports the choice function from the random module and assigns it an alias rc

from faker import Faker
# Faker is a library used for generating fake data, such as names, addresses, and more.

from app import app
from models import db, Owner, Pet

fake = Faker()

with app.app_context():
# starts a context using the app object. This ensures that the code can access the necessary application context for interacting with the database.

    Pet.query.delete()
    # This line deletes all records from the Pet table in the database
    Owner.query.delete()

    owners = []
    # This line starts a loop that will iterate 50 times
    for n in range(50):
        owner = Owner(name=fake.name())
        # creates an instance of the Owner model and assigns a fake name generated by the fake.name() method to the name attribute of the model.
        owners.append(owner)

    db.session.add_all(owners)

    pets = []
    species = ['Dog', 'Cat', 'Chicken', 'Hamster', 'Turtle']
    for n in range(100):
        pet = Pet(name=fake.first_name(), species=rc(species), owner=rc(owners))
        # creates an instance of the Pet model. It assigns a fake first name generated by fake.first_name() to the name attribute, selects a random species from the species list using rc(species), and selects a random owner from the owners list using rc(owners).
        pets.append(pet)

    db.session.add_all(pets)
    db.session.commit()
    